---
title: "Research"
---
<!-- ## Reasearch Interests -->

<!-- My research interests span a wide range of areas in **Statistics** and **Machine Learning**, including high dimensional statistical inference, dimension reduction, and causal inference. Specifically, 
I develop tools for **uncertainty quantification** of iterative algorithms (e.g. estimating prediction risks and constructing confidence intervals for parameters of interest), to improve the reliability of statistical machine learning methods. -->

## Preprints

1. [Uncertainty quantification for iterative algorithms in linear models with application to early stopping](https://arxiv.org/pdf/2404.17856)\
Pierre C. Bellec, **Kai Tan** (2024) (alphabetical order)\
Major revision at the *Annals of Statistics*.

1. [Precise Asymptotics of Bagging Regularized M-estimators](https://arxiv.org/pdf/2409.15252)\
Takuya Koriyama, Pratik Patil, Jin-Hong Du, **Kai Tan**, Pierre C. Bellec (2024)\
Submitted to the *Annals of Statistics*.


1. [Fréchet sufficient variable selection with graphical structure among predictors](https://arxiv.org/pdf/2310.19114).  
Jiaying Weng $^*$ , **Kai Tan** $^*$ ($^*$=equal contribution), Cheng Wang and Zhou Yu (2023)\
Major revision at the *Scandinavian Journal of Statistics*.

## Publications 

1. [Estimating Generalization Performance Along the Trajectory of Proximal SGD in Robust Regression](https://arxiv.org/pdf/2410.02629) \
**Kai Tan**, Pierre C. Bellec (2024)\
Advances in Neural Information Processing Systems (NeurIPS 2024). 
[\[arXiv\]](https://arxiv.org/pdf/2410.02629)[\[Code\]](https://github.com/kaitan365/SGD-generlization-errors)

1. [Corrected generalized cross-validation for finite ensembles of penalized estimators
](https://academic.oup.com/jrsssb/advance-article-abstract/doi/10.1093/jrsssb/qkae092/7760017?redirectedFrom=fulltext) \
Pierre C. Bellec, Jin-Hong Du, Takuya Koriyama, Pratik Patil, **Kai Tan** (2023) (alphabetical order). \
*Journal of the Royal Statistical Society Series B*, to appear. 
[\[arXiv\]](https://arxiv.org/pdf/2310.01374)
[[Code]](https://github.com/kaitan365/CorrectedGCV)

1. [Multinomial Logistic Regression: Asymptotic Normality on Null Covariates in High-Dimensions](https://papers.nips.cc/paper_files/paper/2023/file/e0ac27bf3327c9cb99cc5f548db4f73a-Paper-Conference.pdf)\
**Kai Tan**, and Pierre C. Bellec (2023). \
*Advances in Neural Information Processing Systems* 36 (2024).
[[arXiv]](https://arxiv.org/abs/2305.17825)
[[Code]](https://github.com/kaitan365/Multinomial)



1. [Noise covariance estimation in multi-task high-dimensional linear models](https://projecteuclid.org/journals/bernoulli/volume-30/issue-3/Noise-covariance-estimation-in-multi-task-high-dimensional-linear-models/10.3150/23-BEJ1644.short)\
**Kai Tan**, Gabriel Romon, and Pierre C. Bellec (2023).\
*Bernoulli*. 30.3 (2024): 1695-1722.
[\[arXiv\]](https://arxiv.org/pdf/2206.07256)
[\[slides\]](https://drive.google.com/file/d/1RuESeY7EcA9ohlqQ6HeniyUvhgsk6X7H/view?usp=sharing)
[\[Code\]](https://github.com/kaitan365/Noise-Covariance-Estimation)

1. [Variable dependent partial dimension reduction](https://doi.org/10.1007/s11749-022-00841-y) \
Lu Li, **Kai Tan**, Xuerong Meggie Wen, and Zhou Yu (2023) (alphabetical order).\
*TEST*. 32, 521–541 (2023).

1. [Sparse SIR: optimal rates and adaptive estimation](https://projecteuclid.org/journals/annals-of-statistics/volume-48/issue-1/Sparse-SIR-Optimal-rates-and-adaptive-estimation/10.1214/18-AOS1791.short)\
**Kai Tan**, Lei Shi, and Zhou Yu (2020). \
*The Annals of Statistics* 48.1 (2020): 64-85.

1. [COM-negative binomial distribution: modeling overdispersion and ultrahigh zero-inflated count data](https://link.springer.com/article/10.1007/s11464-018-0714-z)\
Huiming Zhang, **Kai Tan** and Bo Li (2018). \
*Frontiers of Mathematics in China*, 13(4), 967-998.

1. [Summaries of three keynote lectures at the SAE-2018](https://www.tandfonline.com/doi/full/10.1080/24754269.2018.1525658) \
**Kai Tan**, and Lyu Ni (2018). \
*Statistical Theory and Related Fields* 2.2 (2018): 215-218.

1. [Interview with Professor Danny Pfeffermann](https://www.tandfonline.com/doi/full/10.1080/24754269.2018.1520022)\
Lyu Ni, and **Kai Tan** (2018). \
*Statistical Theory and Related Fields* 2.2 (2018): 219-221.
