
---
title: "Teaching"
---

## Independent Instructor

| Term | Course Title | Course Level|
|----------|-----------------------|-----------|
| Summer 2022 | Probability and Stochastic Processes | First-year PhD|
| Spring 2020 | Statistical Methods and Motivations | Undergraduate|
| Fall 2019 | Statistical Methods and Motivations | Undergraduate|

### Teaching Assistant

| Term | Course Title |  Course Level
|----------|-----------------------|-----------|
| Fall 2024 | STAT 534 Stat Learning for Data Science | Master |
| Spring 2024 | STAT 597 Data Wrangling | Master |
| Fall 2022 | STAT 592 Theory of Probability | PhD |
| Spring 2021 | STAT 401 Basic Statistics For Research | Undergraduate |
| Spring 2021 | STAT 211 Statistics I | Undergraduate |
| Fall 2020 | STAT 401 Basic Statistics For Research | Undergraduate |
| Fall 2020 | STAT 211 Statistics I | Undergraduate |
| Spring 2019 | STA 296 Statistical Methods and Motivations | Undergraduate|
| Fall 2018 | STA 296 Statistical Methods and Motivations | Undergraduate|

